### ISSUE TITLE
edit command wrong message for certain indexes

### ISSUE THREAD

**Issue by tituschewxj** [AY2324S2-CS2103T-F13-1/tp#105]
## Currently

Typing `edit 0 n/1` or `edit -1 n/1` just gives `Invalid command format! ...`

## Proposed Fix

The error message should be `The student's index provided is invalid!`
* I would also suggest also changing the error message from `The person index provided is invalid` to `The student's index provided is invalid!`.

**Comment by belligerentbeagle** [comment]
Decided against doing this considering cases where a user needs to change the NusNetID of a student. Implementationly weird and also strange for the user to enter `edit nn/e01234567 nn/e0957499`
