### ISSUE TITLE
Seamless boxes or not?

### ISSUE THREAD

**Issue by tituschewxj** [AY2324S2-CS2103T-F13-1/tp#133]
Should we use seamless boxes or not in our UG/DG?

I prefer not using `seamless` since the border is more well defined. Using `light` looks better personally.

See https://markbind.org/userGuide/components/presentation.html#boxes

**Comment by saiutkarsh33** [comment]
<img width="894" alt="Screenshot 2024-04-04 at 5 46 20 PM" src="https://github.com/AY2324S2-CS2103T-F13-1/tp/assets/122259179/59bf96be-62f7-4d59-a0dc-44fedcc0d25e">
Want to use this one

**Comment by tituschewxj** [comment]
This issue has been resolved from #271
