### ISSUE TITLE
[PE-D][Tester D] Functionality Bug: Tag field error in addstu command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-1/tp#169]
Command to reproduce bug:
`addstu n/Student One nn/E1234984 t/why so hard`

The user guide and error message state that the tags names should be alphanumeric. However, the above command will cause an error. 

Likely, the application does not support tag with spaces. I would recommend the team to either allow spaces or update the user guide and error message to specify that spaces are not allowed.

In addition, I feel that this issue might be medium severity if the user use it frequently. I will keep it at low severity as tag is an optional field.

![image.png](https://raw.githubusercontent.com/guohuang88/ped/main/files/f94d5919-4359-4cc1-b7bf-127433d1dc47.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: guohuang88/ped#2

**Comment by ForAeons** [comment]
The term "alphanumeric" typically refers to a combination of alphabetic and numeric characters. This includes letters (A-Z, both uppercase and lowercase) and numbers (0-9). When something is described as alphanumeric, it usually means that only these characters are permitted, and, in a strict sense, this does not include spaces or special characters.

**Comment by tituschewxj** [comment]
Todo:
- [ ] update the user guide to state clearly that tag keywords must be a single string not separated by space.
- [ ] See also #205
