### ISSUE TITLE
[PE-D][Tester E] Error in UG 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-1/tp#179]
Pressing the Down Key doesnt work, can remove:

![BF589919-ECA4-47B5-AD05-9AB4089DAD0C.jpeg](https://raw.githubusercontent.com/qinxutan/ped/main/files/1eb04f6c-62a6-4c9d-bf7c-744612f7c98c.jpeg)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: qinxutan/ped#7

**Comment by tituschewxj** [comment]
This is a documentation bug, as we did not give sufficient examples on how to use the down key.

Todo
- [ ] Add more documentation for using command retrieval

**Comment by belligerentbeagle** [comment]
Fixed in #270
