### ISSUE TITLE
[PE-D][Tester C] Adding students with multiple copies of TAPro active

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-1/tp#187]
![image.png](https://raw.githubusercontent.com/eliotlee68/ped/main/files/9a817da7-e455-4a7e-8342-d26d0ef8766c.png)

When having 2 copies of TAPro active, if I were to use addstu in both copies to add two students and close both applications, upon reopening TAPro, I would find that only one addstu 
function was recorded

![image.png](https://raw.githubusercontent.com/eliotlee68/ped/main/files/064a6ff7-f28e-4b08-8ebd-fcd5bc55d673.png)

Steps to reproduce
Have 2 copies of TAPro active
in each copy: use addstu to add a student to the list
close both copies
open TAPro again

expected: the student list should contain both of the added students (in this case, Name 1 AND Name 2 should be present)
actual: Only Student 2 is present on the list

**Note** While this bug may sound relatively niche and difficult to reproduce, the way I discovered this was I forgot I had the application open and ended up with 2 copies active at the same time, which led to this bug being discovered, so having multiple copies of TAPro active at one point is realistically a situation that could happen (unless I'm just very clumsy)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: eliotlee68/ped#5

**Comment by tituschewxj** [comment]
This is a documentation bug. We need to add in the known issues section that opening multiple copies of TAPro will cause the data to desync.
