### ISSUE TITLE
[PE-D][Tester B] Typos in the Command Summary for UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-1/tp#192]
Minor typo in the example command. ```add``` instead of ```addstu```.
  
![image.png](https://raw.githubusercontent.com/azumieflare/ped/main/files/12a87b33-8082-474d-822d-8d97df42501f.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: azumieflare/ped#8

**Comment by belligerentbeagle** [comment]
good bug
