### ISSUE TITLE
[PE-D][Tester A] Find accepts arguments that do not follow name format

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-1/tp#195]
![image.png](https://raw.githubusercontent.com/LWS49/ped/main/files/5492f2a9-00c6-4173-a807-42223918417e.png)
Find should have raised an error when arguments that do not follow the formatting restriction of name is passed into it.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: LWS49/ped#14

**Comment by tituschewxj** [comment]
Severity is very low as this does not impact the user.

**Comment by tituschewxj** [comment]
Should make this a `response.NotInScope` by doing the following:
- [ ] Specify in the UG that find's parameter has no constraints, i.e. it can be alphanumeric and special characters, etc.

Rectifying this is of minimal importance, as it does not impact the user usage in any way.
