### ISSUE TITLE
[PE-D][Tester B] Duplicate students with same phone/email can be added. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-1/tp#198]
2 or more students with almost the same details can be added. The only field that has to be different is the NUSNET_ID. 

Perhaps there should be a check for this as well?

![image.png](https://raw.githubusercontent.com/azumieflare/ped/main/files/9d57d426-21fc-4574-8531-8bd9b70ed8d9.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: azumieflare/ped#11

**Comment by belligerentbeagle** [comment]
Erm... this is why nusnet is a unique identifier, stated in the UG. Should there be a "known issue" of how you can key in identical email and hp number?
